# Generated by Django 3.2.4 on 2023-03-16 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordImage',
            fields=[
                ('upload', models.ImageField(help_text='загрузите картинку', upload_to='uploads/preview/%Y/%m', verbose_name='картинка')),
                ('word', models.OneToOneField(help_text='выберете слово', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='words.word', verbose_name='слово')),
            ],
            options={
                'verbose_name': 'картинка слова',
                'verbose_name_plural': 'картинки слов',
            },
        ),
    ]
